import = ["/home/gmiyazaki/.config/alacritty/themes/tokyo-night.toml"]

[window]
opacity = 0.80

[window.padding]
x = 16
y = 16

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[shell]
program = "/usr/bin/zsh"

