import = ["/home/gmiyazaki/.config/alacritty/themes/dracula.toml"]

[window]
opacity = 0.7

[window.padding]
x = 16
y = 16

[font]
size = 10.0

[font.normal]
family = "MesloLGS Nerd Font"

[shell]
program = "/usr/bin/zsh"
