local colors = require('styles.colors')

vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = colors.red, bg = colors.black2 })
vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = colors.darker_black })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = colors.black, bg = colors.green })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = colors.black, bg = colors.red })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { fg = colors.white, bg = colors.black2 })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffAdd', { fg = colors.green })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffChange', { fg = colors.yellow })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffDelete', { fg = colors.red })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = colors.blue, bg = colors.one_bg })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = colors.darker_black, bg = colors.darker_black })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = colors.black2, bg = colors.black2 })
vim.api.nvim_set_hl(0, 'TelescopePromptNormal', { fg = colors.white, bg = colors.black2 })
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { fg = colors.darker_black, bg = colors.darker_black })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = colors.red, bg = colors.black2 })
