#!/usr/bin/env bash

windows=$(hyprctl clients -j | jq -r ".[] 
| select(.workspace.id==$1) 
| select(.focushistoryid!=0) 
| .address")

for window in $windows; do
  hyprctl dispatch closewindow address:$window
done
