#CopyQ
windowrule {
  name = windowrule-1
  float = on
  move = (100) (50)
  match:class = (com.github.hluk.copyq)
}

windowrule {
  name = windowrule-2
  size = 400 800
  match:class = (com.g5ithub.hluk.copyq)
}

#Flameshot
windowrule {
  name = windowrule-3
  no_anim = on
  float = on
  move = (0) (0)
  pin = on
  monitor = 1
  match:class = ^(flameshot)$
}

#FileRoller
windowrule {
  name = windowrule-4
  no_anim = on
  float = on
  match:class = ^(org.gnome.FileRoller)$
}

#Thunar Rename
windowrule {
  name = windowrule-5
  float = on
  match:class = thunar
  match:initial_title = ^(Rename.*)
}

